/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['fut.js']) {
  _$jscoverage['fut.js'] = [];
  _$jscoverage['fut.js'][1] = 0;
}
_$jscoverage['fut.js'][1]++;
exports.instrumented = true;
_$jscoverage['fut.js'].source = ["exports.instrumented = true;"];
